LiftServiceWebApp/Models/Payment/AddressModel.cs
namespace LiftServiceWebApp.Models.Payment
{
    public class AddressModel
    {
        public string Description { get; set; }
        public string ZipCode { get; set; }
        public string ContactName { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    }
}

LiftServiceWebApp/Models/Payment/BasketModel.cs
namespace LiftServiceWebApp.Models.Payment
{
    public class BasketModel
    {
        public string Id { get; set; }
        public string Price { get; set; }
        public string Name { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string ItemType { get; set; }
    }
}

LiftServiceWebApp/Models/Payment/CardModel.cs
namespace LiftServiceWebApp.Models.Payment
{
    public class CardModel
    {
        public string CardHolderName { get; set; }
        public string CardNumber { get; set; }
        public string ExpireYear { get; set; }
        public string ExpireMonth { get; set; }
        public string Cvc { get; set; }
    }
}

LiftServiceWebApp/Models/Payment/CustomerModel.cs
namespace LiftServiceWebApp.Models.Payment
{
    public class CustomerModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string IdentityNumber { get; set; }
        public string Email { get; set; }
        public string GsmNumber { get; set; }
        public string RegistrationDate { get; set; }
        public string LastLoginDate { get; set; }
        public string RegistrationAddress { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string Ip { get; set; }
    }
}

LiftServiceWebApp/Models/Payment/InstallmentModel.cs
using System.Collections.Generic;

namespace LiftServiceWebApp.Models.Payment
{
    public class InstallmentModel
    {
        public string BinNumber { get; set; }
        public int Commercial { get; set; }
        public string Price { get; set; }
        public string CardType { get; set; }
        public string CardAssociation { get; set; }
        public string CardFamilyName { get; set; }
        public int? Force3Ds { get; set; }
        public long? BankCode { get; set; }
        public string BankName { get; set; }
        public int? ForceCvc { get; set; }
        public List<InstallmentPriceModel> InstallmentPrices { get; set; }
    }
}

LiftServiceWebApp/Models/Payment/InstallmentPriceModel.cs
namespace LiftServiceWebApp.Models.Payment
{
    public class InstallmentPriceModel
    {
        public string Price { get; set; }
        public string TotalPrice { get; set; }
        public int? InstallmentNumber { get; set; }
    }
}

LiftServiceWebApp/Models/Payment/IyzicoPaymentOptions.cs
using Iyzipay;

namespace LiftServiceWebApp.Models.Payment
{
    public class IyzicoPaymentOptions:Options
    {
        public const string Key = "IyzicoOptions";
        public string ThreedsCallbackUrl { get; set; }
    }
}

LiftServiceWebApp/Models/Payment/PaymentModel.cs
using System.Collections.Generic;

namespace LiftServiceWebApp.Models.Payment
{
    public class PaymentModel
    {
        public string PaymentId { get; set; }
        public decimal Price { get; set; }
        public decimal PaidPrice { get; set; }
        public int Installment { get; set; }
        public CardModel CardModel { get; set; }
        public List<BasketModel> BasketList { get; set; }
        public CustomerModel Customer { get; set; }
        public AddressModel Address { get; set; }
        public string Ip { get; set; }
        public string UserId { get; set; }
    }
}

LiftServiceWebApp/Models/Payment/PaymentResponseModel.cs
namespace LiftServiceWebApp.Models.Payment
{
    public class PaymentResponseModel
    {
        public string Price { get; set; }
        public string PaidPrice { get; set; }
        public int? Installment { get; set; }
        public string Currency { get; set; }
        public string PaymentId { get; set; }
        public string PaymentStatus { get; set; }
        public int? FraudStatus { get; set; }
        public string MerchantCommissionRate { get; set; }
        public string MerchantCommissionRateAmount { get; set; }
        public string PosCommissionRateAmount { get; set; }
        public string PosCommissionFee { get; set; }
        public string CardType { get; set; }
        public string CardAssociation { get; set; }
        public string CardFamily { get; set; }
        public string CardToken { get; set; }
        public string CardUserKey { get; set; }
        public string BinNumber { get; set; }
        public string LastFourDigits { get; set; }
        public string BasketId { get; set; }
    }
}

LiftServiceWebApp/ViewModels/PaymentViewModel.cs
using LiftServiceWebApp.Models.Payment;

namespace LiftServiceWebApp.ViewModels
{
    public class PaymentViewModel
    {
        public CardModel CardModel { get; set; }
        public AddressModel AddressModel { get; set; }
        public BasketModel BasketModel { get; set; }
        public decimal Amount { get; set; }
        public decimal PaidAmount { get; set; }
        public int Installment { get; set; }
    }
}

LiftServiceWebApp/Controllers/PaymentController.cs
using LiftServiceWebApp.Extensions;
using LiftServiceWebApp.Models.Payment;
using LiftServiceWebApp.Services;
using LiftServiceWebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace LiftServiceWebApp.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IPaymentService _paymentService;

        public PaymentController(IPaymentService paymentService)
        {
            _paymentService = paymentService;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult CheckInstallment(string binNumber)
        {
            if (binNumber.Length != 6)
                return BadRequest(new
                {
                    Message = "Bad req."
                });

            var result = _paymentService.CheckInstallments(binNumber, 1000);
            return Ok(result);
        }
        [Authorize]
        [HttpPost]
        public IActionResult Index(PaymentViewModel model)
        {
            var paymentModel = new PaymentModel()
            {
                Installment = model.Installment,
                Address = new AddressModel(),
                BasketList = new List<BasketModel>(),
                Customer = new CustomerModel(),
                CardModel = model.CardModel,
                Price = 1000,
                UserId = HttpContext.GetUserId(),
                Ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString()
            };
            var installmentInfo = _paymentService.CheckInstallments(paymentModel.CardModel.CardNumber.Substring(0, 6), paymentModel.Price);

            var installmentNumber =
                installmentInfo.InstallmentPrices.FirstOrDefault(x => x.InstallmentNumber == model.Installment);

            paymentModel.PaidPrice = decimal.Parse(installmentNumber != null ? installmentNumber.TotalPrice.Replace('.', ',') : installmentInfo.InstallmentPrices[0].TotalPrice.Replace('.', ','));

            //legacy code
            var result = _paymentService.Pay(paymentModel);
            return View();
        }
    }
}

LiftServiceWebApp/Controllers/TechnicianController.cs
using LiftServiceWebApp.Data;
using LiftServiceWebApp.Extensions;
using LiftServiceWebApp.Models.Entities;
using LiftServiceWebApp.Models.Identity;
using LiftServiceWebApp.Repository;
using LiftServiceWebApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LiftServiceWebApp.Controllers
{
    public class TechnicianController : Controller
    {
        private readonly FailureRepo _failureRepo;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly ProductRepo _productRepo;
        public TechnicianController(
            FailureRepo failureRepo,
            UserManager<ApplicationUser> userManager,
            RoleManager<ApplicationRole> roleManager,
            ProductRepo productRepo)
        {
            _failureRepo = failureRepo;
            _userManager = userManager;
            _roleManager = roleManager;
            _productRepo = productRepo;
        }

        public async Task<IActionResult> GetFailures()
        {
            var technician = await _userManager.FindByIdAsync(HttpContext.GetUserId());
            var failures = _failureRepo.GetByTechnicianId(technician.Id).ToList();

            return View(failures);
        }      
        [HttpPost]
        public async Task<IActionResult> GetFailures(string failureId)
        {
            var failure = _failureRepo.GetById(Guid.Parse(failureId));
     
            failure.FailureState = FailureStates.KabulEdildi;
            _failureRepo.Update(failure);

            var technician = await _userManager.FindByIdAsync(HttpContext.GetUserId());
            var failures = _failureRepo.GetByTechnicianId(technician.Id).ToList();
            return View(failures);
        }

        [HttpPost]
        public IActionResult Payment(PaymentIdViewModel paymentIdViewModel)
        {
            var products = _productRepo.Get().ToList();
            return View(products);
        }

        
    }
}

LiftServiceWebApp/Views/Technician/GetFailures.cshtml
@{ ViewBag.Title = "Arızalar";}
@model List<Failure>

<Style>
    .ss_two_sec:after {
        background: white;
    }
</Style>

<div class="container-fluid ss_service_one ss_section_sec_bg spacer_top spacer_bottom ss_two">
    <div class="row">

        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="ss_two_sec wow fadeIn" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeIn;">

                <h1>Arızalar</h1><br />

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Arıza</th>
                            <th scope="col">Arıza Detay</th>
                            <th scope="col">Adres</th>
                            <th scope="col">Oluşturulma Tarihi</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 1; i <= Model.Count(); i++)
                        {
                            <tr>
                                <th scope="row">@i</th>
                                <td>@Model[i - 1].FailureName</td>
                                <td>@Model[i - 1].FailureDescription</td>
                                <td>@Model[i - 1].AddressDetail</td>
                                <td>@Model[i - 1].CreatedDate</td>
                                <td>
                                    @{
                                        if (i == 1)
                                        {
                                            if (Model[0].FailureState == FailureStates.KabulEdildi)
                                            {
                                                <form method="post" asp-action="Payment" asp-controller="Technician">
                                                    <input type="hidden" asp-for="@Model[0].UserId" name="UserId" />
                                                    <input type="hidden" asp-for="@Model[0].TechnicianId" name="TechnicianId" />
                                                    <input type="hidden" asp-for="@Model[0].Id" name="FailureId"/>
                                                    <button class="btn btn-outline-primary">ÜCRETLENDİR</button>
                                                </form>
                                            }
                                            else
                                            {
                                                <form method="post" asp-action="GetFailures" asp-controller="Technician">
                                                    <input type="hidden" asp-for="@Model[0].Id" name="failureId" />
                                                    <button class="btn btn-outline-primary">KABUL ET</button>
                                                </form>
                                            }
                                        }
                                        else
                                        {
                                            <h6>Sırada Bekliyor</h6>
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>